from tkinter import *
def doNothing():
    print("ok ok I won't")
root=Tk()
menu=Menu(root)
root.config(menu=menu)

subMenu=Menu(menu)
menu.add_cascade(label='File', menu=subMenu)
subMenu.add_command(label="New Project",command=doNothing)
subMenu.add_command(label='New...',command=doNothing)
subMenu.add_separator()
subMenu.add_command(label="Exit",command=root.quit)
editMenu=Menu(menu)
subMenu2=Menu(menu)
subMenu2.add_command(label='Cut')
subMenu2.add_command(label='Copy')
subMenu2.add_command(label='Paste')
menu.add_cascade(label="Edit",menu=subMenu2)
root.mainloop()